spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  datasource:
    hikari:
      driverClassName: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always


server:
  port: 8090